version: '3.5'

services: 
    tests:
      container_name: tests
      build:
        context: .
        dockerfile: tests.dockerfile
      environment:
        - AWS_DEFAULT_REGION=ap-southeast-2
        - AWS_ACCESS_KEY_ID=123
        - AWS_SECRET_ACCESS_KEY=123
        - LOCALSTACK_HOST=localstack
      depends_on:
        - localstack
        - test-infra-setup