version: '3.5'

services: 
    localstack:
      image: localstack/localstack:latest
      ports:
        - 4566:4566
      environment:
        - SERVICES=dynamodb

    test-infra-setup:
      image: amazon/aws-cli
      volumes:
        - ./test-infra-setup.sh:/app/test-infra-setup.sh
      environment:
        - AWS_DEFAULT_REGION=ap-southeast-2
        - AWS_ACCESS_KEY_ID=123
        - AWS_SECRET_ACCESS_KEY=123
      depends_on:
        - localstack
      entrypoint: bash /app/test-infra-setup.sh